name: "Terraform-branch-Infra-Apply"

on:
  push:
    branches:
      - FutureBranch1

jobs:
   terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: 'us-east-1'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-Terraform@v1
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Paln
      id: paln
      if: github.event_name == 'push'
      run: terraform plan -no-color
      continue-on-error: true
